// Standalone build for <supernote-viewer> (issue #183) - a *separate*
// bundle from esbuild.config.mjs's Obsidian plugin build, entered from
// src/webcomponent/SupernoteViewerElement.ts, which (unlike src/main.ts)
// never imports `obsidian`. Node built-ins are still marked `external`
// rather than omitted outright: if something ever did pull one in by
// mistake, that should fail this build loudly (there's no browser shim for
// it here) rather than bundle silently and break at runtime in an actual
// browser instead.
import esbuild from "esbuild";
import process from "process";
import path from "path";
import { fileURLToPath } from "url";
// Node's own builtin-module list - the community-plugin scan (issue
// #228) flags the `builtin-modules` npm package, which on modern Node is
// only a thin filter over this.
import { builtinModules } from "node:module";
import inlineWorkerPlugin from "esbuild-plugin-inline-worker";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/webcomponent/SupernoteViewerElement.ts"],
	alias: {
		// supernote-typescript is a git submodule developed alongside this
		// plugin, not an npm dependency (see CLAUDE.md) - point straight at
		// it rather than through a node_modules symlink, which npm install
		// prunes/reaches through and deletes the submodule's own
		// node_modules.
		'supernote-typescript': path.join(__dirname, 'supernote-typescript'),
	},
	bundle: true,
	plugins: [inlineWorkerPlugin()],
	external: [...builtinModules],
	format: "esm",
	target: "es2020",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "dist/supernote-viewer.js",
	minify: prod,
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
