import esbuild from "esbuild";
import process from "process";
import path from "path";
import { fileURLToPath } from "url";
// Node's own builtin-module list - the community-plugin scan (issue
// #228) flags the `builtin-modules` npm package, which on modern Node is
// only a thin filter over this.
import { builtinModules } from "node:module";
import inlineWorkerPlugin from "esbuild-plugin-inline-worker";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	alias: {
		// supernote-typescript is a git submodule developed alongside this
		// plugin, not an npm dependency (see CLAUDE.md) - point straight at
		// it rather than through a node_modules symlink, which npm install
		// prunes/reaches through and deletes the submodule's own
		// node_modules.
		'supernote-typescript': path.join(__dirname, 'supernote-typescript'),
	},
	bundle: true,
	loader: {
		// sql.js's wasm binary (used by SupernoteAtelier for .spd files) is
		// embedded directly in the bundle rather than fetched/read at
		// runtime, so it works the same on desktop (Node/Electron) and
		// mobile (browser) Obsidian without a locateFile() callback.
		'.wasm': 'binary',
	},
	// inlineWorkerPlugin() runs a wholly separate, nested esbuild.build()
	// call for every *.worker.ts file (see its own README/source) - that
	// nested build does NOT inherit this config's own `loader` above, only
	// whatever's passed as its own argument here, so atelierComposite
	// .worker.ts's identical sql.js wasm import (via render/atelierRenderer
	// .ts's openAtelierBuffer()) needs the same loader entry repeated
	// explicitly.
	plugins: [inlineWorkerPlugin({ loader: { '.wasm': 'binary' } })],
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
