// Standalone build for <supernote-atelier-viewer> - the `.spd` (Supernote
// Atelier) equivalent of esbuild.webcomponent.config.mjs, entered from
// src/webcomponent/SupernoteAtelierViewerElement.ts, which (like that
// file's own `.note` sibling) never imports `obsidian`. See that config's
// own header comment for why Node built-ins are marked external rather than
// omitted outright.
import esbuild from "esbuild";
import process from "process";
import path from "path";
import { fileURLToPath } from "url";
import builtins from "builtin-modules";
import inlineWorkerPlugin from "esbuild-plugin-inline-worker";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/webcomponent/SupernoteAtelierViewerElement.ts"],
	alias: {
		// supernote-typescript is a git submodule developed alongside this
		// plugin, not an npm dependency (see CLAUDE.md) - point straight at
		// it rather than through a node_modules symlink, which npm install
		// prunes/reaches through and deletes the submodule's own
		// node_modules.
		'supernote-typescript': path.join(__dirname, 'supernote-typescript'),
	},
	bundle: true,
	loader: {
		// sql.js's wasm binary (used by SupernoteAtelier to parse .spd
		// files) is embedded directly in the bundle rather than fetched/
		// read at runtime - same reasoning as esbuild.config.mjs's
		// identical loader entry: this way it works the same whether
		// hosted from a plain static file server or bundled into another
		// app, with no locateFile() callback for a consumer to wire up.
		'.wasm': 'binary',
	},
	// atelierComposite.worker.ts (the compositing Worker
	// SupernoteAtelierViewerElement.ts/render/atelierWorkerClient.ts talk
	// to, so real compositing work never blocks the main thread) needs
	// esbuild-plugin-inline-worker the same way rasterize.worker.ts does in
	// esbuild.config.mjs/esbuild.webcomponent.config.mjs - see this
	// config's own `loader` comment above for why its own `.wasm` loader
	// also has to be repeated into the plugin's nested build here, not just
	// declared once at this level.
	plugins: [inlineWorkerPlugin({ loader: { '.wasm': 'binary' } })],
	external: [...builtins],
	format: "esm",
	target: "es2020",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "dist/supernote-atelier-viewer.js",
	minify: prod,
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
